/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uhfhgavOkS6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Calender() {
  return (
    <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
      <div className="flex items-center justify-between">
        <div className="text-lg font-medium">May 2024</div>
        <div className="flex items-center gap-2">
          <Button size="icon" variant="ghost">
            <ChevronLeftIcon className="h-4 w-4" />
          </Button>
          <Button size="icon" variant="ghost">
            <ChevronRightIcon className="h-4 w-4" />
          </Button>
        </div>
      </div>
      <div className="mt-4 grid grid-cols-7 gap-2">
        <div className="text-center text-xs font-medium text-gray-500 dark:text-gray-400">Sun</div>
        <div className="text-center text-xs font-medium text-gray-500 dark:text-gray-400">Mon</div>
        <div className="text-center text-xs font-medium text-gray-500 dark:text-gray-400">Tue</div>
        <div className="text-center text-xs font-medium text-gray-500 dark:text-gray-400">Wed</div>
        <div className="text-center text-xs font-medium text-gray-500 dark:text-gray-400">Thu</div>
        <div className="text-center text-xs font-medium text-gray-500 dark:text-gray-400">Fri</div>
        <div className="text-center text-xs font-medium text-gray-500 dark:text-gray-400">Sat</div>
        <div className="text-center text-sm font-medium text-gray-500 dark:text-gray-400">29</div>
        <div className="text-center text-sm font-medium text-gray-500 dark:text-gray-400">30</div>
        <div className="text-center text-sm font-medium text-gray-500 dark:text-gray-400">1</div>
        <div className="text-center text-sm font-medium text-gray-500 dark:text-gray-400">2</div>
        <div className="text-center text-sm font-medium text-gray-500 dark:text-gray-400">3</div>
        <div className="text-center text-sm font-medium text-gray-500 dark:text-gray-400">4</div>
        <div className="text-center text-sm font-medium text-gray-500 dark:text-gray-400">5</div>
        <div className="text-center text-sm font-medium">6</div>
        <div className="text-center text-sm font-medium">7</div>
        <div className="text-center text-sm font-medium">8</div>
        <div className="text-center text-sm font-medium">9</div>
        <div className="text-center text-sm font-medium">10</div>
        <div className="text-center text-sm font-medium">11</div>
        <div className="text-center text-sm font-medium">12</div>
        <div className="text-center text-sm font-medium">13</div>
        <div className="text-center text-sm font-medium">14</div>
        <div className="text-center text-sm font-medium">15</div>
        <div className="text-center text-sm font-medium">16</div>
        <div className="text-center text-sm font-medium">17</div>
        <div className="text-center text-sm font-medium">18</div>
        <div className="text-center text-sm font-medium">19</div>
        <div className="text-center text-sm font-medium">20</div>
        <div className="text-center text-sm font-medium">21</div>
        <div className="text-center text-sm font-medium">22</div>
        <div className="text-center text-sm font-medium">23</div>
        <div className="text-center text-sm font-medium">24</div>
        <div className="text-center text-sm font-medium">25</div>
        <div className="text-center text-sm font-medium">26</div>
        <div className="text-center text-sm font-medium">27</div>
        <div className="text-center text-sm font-medium">28</div>
        <div className="text-center text-sm font-medium">29</div>
        <div className="text-center text-sm font-medium">30</div>
        <div className="text-center text-sm font-medium text-gray-500 dark:text-gray-400">31</div>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
